main:
  params: [input]

  steps:
    - initialize:
        assign:
          - bucket: $${input.bucket}
          - object: $${input.object}
          - generation: $${input.generation}
          - gcs_uri: $${"gs://" + bucket + "/" + object}

    - logBucket:
        call: sys.log
        args:
          text: $${bucket}

    - logObject:
        call: sys.log
        args:
          text: $${object}

    - completed:
        return:
          status: "SUCCESS"
          bucket: $${bucket}
          object: $${object}